
site_name: pnp32
site_description: Modular motion ecosystem for OpenPnP using SPI drivers and ESP32
site_author: Pavol Krnac

# Repository
repo_name: pnp32
repo_url: https://github.com/palo-krnac/pnp32

# Copyright
copyright: Copyright &copy; 2024 - 2025 Pavol Krnac
# Configuration
site_dir: site
docs_dir: docs
theme:
  name: material
  
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
    - content.code.annotate
    - content.tabs.link
    - content.action.edit
    - content.tooltips

palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
font:
    text: Roboto
    code: Roboto Mono
favicon: assets/favicon.png
icon:
    logo: logo   

# Plugins


# Hooks
#hooks:
 # - material/overrides/hooks/shortcodes.py
 # - material/overrides/hooks/translations.py   

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/palo-krnac/pnp32

  announcement:

  #language: en
  #logo: assets/logo.png
  #favicon: assets/favicon.ico


  icon:
    repo: fontawesome/brands/github

# Extensions
markdown_extensions:
  - admonition
  - tables
  - footnotes
  - codehilite
  - attr_list
  - toc:
       permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.tasklist
  - pymdownx.highlight




nav:
  - Home: index.md
  - Hardware: 
    - Overview: hardware/hardware.md
    - Boards: 
      - pnp32-MC: hardware/boards/pnp32-MC.md
      - pnp32-MCM: hardware/boards/pnp32-MCM.md
      - pnp32-MCH: hardware/boards/pnp32-MCH.md
    - Drivers:   
      - TMC5130: hardware/drivers/TMC5130.md
      - TMC5160: hardware/drivers/TMC5160.md
      - powerSTEP01: hardware/drivers/powerstep01.md
  - Firmware: hardware/firmware.md
  - Mechanical: MECHANICAL/mechanical.md
  - openPNP: 
    - Commands: openPNP/commands.md
    - Basic codes: openPNP/basic_code.md
    - Machine codes: openPNP/machine_code.md
    - Actuators codes: openPNP/actuators_code.md
    - Safety codes: openPNP/safety_code.md
 



